# Generated by Django 4.2.19 on 2025-02-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_ems', '0002_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
